ce_portal/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.static import serve


urlpatterns = [
    path('city/', include('city.urls')),
     path('registration/', include('registration.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns +=static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

city/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.landing, name = 'landing-page'),
    path('dashboard/<int:pk>', views.dashboard, name = 'dashboard-template'),
    path('team/', views.teamForm, name='team-form')
]

mysite/urls.py
from django.contrib import admin
from django.urls import path
from projectApp import views as project_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('entry/',project_views.create,name='entry')
]

urls.py
from django.contrib import admin
from django.urls import path
from projectApp import views as project_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('entry/',project_views.create,name='entry')
]

city/models.py
from django.db import models

# Create your models here.

class City(models.Model):
    cityName = models.CharField(max_length=100)
    cityImage = models.ImageField(default='dcity.jpg',upload_to='city_pics')
    cityCompetitions = models.ManyToManyField('Competition')

    def __str__(self):
        return self.cityName

    

class Competition(models.Model):
    competitionName = models.CharField(max_length=100)
    competitionDescription = models.TextField()
    competitionImage1 = models.ImageField(default='dcomp1.jpg',upload_to='competition_pics')
    competitionImage2 = models.ImageField(default='dcomp2.jpg',upload_to='competition_pics')

    def __str__(self):
        return self.competitionName

class Applicant(models.Model):
    name =models.CharField(max_length=50)
    city = models.ForeignKey(City,on_delete = models.CASCADE)
    competition = models.ForeignKey(Competition, on_delete=models.PROTECT) #should we use cascade?
    email =  models.EmailField()

    def __str__(self):
        return self.name

class Team(models.Model):
    name = models.CharField(max_length=100)
    members = models.ManyToManyField(Applicant)

    def __str__(self):
        return self.name

city/forms.py
from django import forms
from .models import Team, Applicant


from django.forms import ModelForm
  
class EntryForm(ModelForm):
  
    class Meta:
        model = Applicant
        fields = ['competition','city']

city/views.py
from django.shortcuts import render
from .models import Applicant, City , Competition, Team
from django.shortcuts import render
from .forms import EntryForm
from django.http import HttpResponseRedirect

def landing(request) :
    context = {
        'cities': City.objects.all(),
    }
    return render(request, 'city/landing.html',context)

def dashboard(request,pk) :
    city = City.objects.get(pk=pk)
    data = {
        'city' : city,
        'competitions': city.cityCompetitions.all(),
    }
    return render(request, 'city/dashboard.html',data)

def teamForm(request):
    if request.method == 'POST':
        form = EntryForm(request.POST)

        data = request.POST
        for i in range( int(data.get('number'))):
            # print(data.get('city'),data.get('competition'))
            applicant = Applicant(name = data.get('name' + str(i)), email = data.get('email' + str(i)), city = data.get('city'), competition = data.get('competition'))
            applicant.save()
            # print('success' + str(i))
        team = Team(name = data.get('name'),)
        print(data)
        # team.save()
        return render(request, 'form/success.html', {'form': form})

    # if a GET (or any other method) we'll create a blank for
    else:
        form = EntryForm()
        return render(request, 'form/team.html',{'form': form})
# Create your views here.

city/templates/form/success.html
<h1>Done</h1>

city/templates/form/team.html
{% load static %}
{% load crispy_forms_tags %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    <form action="" method=POST>
        {% csrf_token %}
        <input type="hidden" name="number" value=1 id="num">
        <div id="main">
            <div id="a">
                <h1>Team</h1>
                <p>
                    <label for="id_name"> Team Name:</label>
                    <input type="text" name="name" maxlength="50" required="" id="id_name">
                </p>
                <p>
                    <label for="id_city"> City:</label>
                    {{ form.city }}
                </p>
                <p>
                    <label for="id_competition">Competition:</label>
                    {{ form.competition }}
                </p>
            </div>
            <div id="a">
                <h1>Candidate 1</h1>
                <p>
                    <label for="id_name">Name:</label>
                    <input type="text" name="name0" maxlength="50" required="" id="id_name">


                </p>
                <p>
                    <label for="id_email">Email:</label>
                    <input type="email" name="email0" maxlength="254" required="" id="id_email">
                </p>
            </div>
        </div>
        <button id="button1">Add</button>
        <button class="button" type="submit"><span style="color:red"><b>Register</b></span></button>
    </form>
</body>
<script src="{% static 'form/button.js' %}">
</script>

</html>